### ISSUE TITLE
Problem running serving

### ISSUE THREAD

**Issue by xiamx** [dsindex/syntaxnet#10]
H,

I was following https://github.com/dsindex/syntaxnet/blob/master/README_api.md and got an error at this step:

```
$ bazel --output_user_root=bazel_root build --nocheck_visibility -c opt -s //tensorflow_serving/example:parsey_api --genrule_strategy=standalone --spawn_strategy=standalone --verbose_failures



Extracting Bazel installation...
.........
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path.
INFO: Elapsed time: 1.905s

```

**Comment by dsindex** [comment]
@xiamx 

it seems that there is a problem on configuring GPUs. 
let's leave this problem away for a while. 

is it possible to install tensorflow_serving ? 

https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md

**Comment by xiamx** [comment]
@dsindex 

Tried building tensorflow_serving following the document you provided, had no problem.

It seems the problem lies somewhere in api/modified_workspace.bzl and api/append_BUILD
These changes perhaps interfered with automatic cuda detection.

Which commit of https://github.com/tensorflow/serving are you using?  Perhaps recent changes broke it.

**Comment by dsindex** [comment]
@xiamx 

i got it. 

```
$ git clone --recurse-submodules https://github.com/tensorflow/serving
# checkout proper version of tf_models
$ cd serving/tf_models
$ git checkout a4b7bb9a5dd2c021edcd3d68d326255c734d0ef0
```

i used this version of `serving`

```
$ cd serving
$ git log
commit 89e9dfbea055027bc31878ee8da66b54a701a746
Merge: 30fffbd 7e1fd50
Author: Sukriti Ramesh <sukritiramesh@google.com>
Date:   Thu Aug 18 18:59:26 2016 -0700

    Merge pull request #161 from sukritiramesh/branch_130454325

    Branch 130454325
...
```

**Comment by xiamx** [comment]
Thanks @dsindex problem solved :)

**Comment by johndpope** [comment]
nice. I'll update my docker script.

**Comment by johndpope** [comment]
still no joy for me - either running on mac / or in docker.

<img width="986" alt="screen shot 2016-10-18 at 21 30 07" src="https://cloud.githubusercontent.com/assets/289994/19502291/f87a0ad6-9579-11e6-909d-5b61b2f41cba.png">

https://gist.githubusercontent.com/johndpope/fc1c2327a4ae255d9c44dda9b67b5288/raw/342d0692287f06c97fcb97102190f86275ba3de5/parseyapi.sh

I think there must  be some build variable / or path setup or something.
I tried adding
export TF_NEED_CUDA=0 
my mac doesn't have nvidia which sucks. I added this ticket to tensorflow
https://github.com/tensorflow/serving/issues/200

**Comment by xiamx** [comment]
@johndpope 

When you run

`git clone --recurse-submodules https://github.com/tensorflow/serving`
This will clone `serving` as well as submodule `serving/tensorflow` pointed by the HEAD of `serving`.
Commit `89e9dfbea055027bc31878ee8da66b54a701a746` of serving does not use the same `serving/tensorflow` as the HEAD of serving.

When you `git checkout 89e9dfbea055027bc31878ee8da66b54a701a746` inside `serving`, it does not update `serving/tensorflow` submodule for you. so maybe you need to run additionally `git submodule update --init --recursive`

**Comment by dsindex** [comment]
thank you @xiamx 

@johndpope

sorry for my lazy testing. i tested instructions and found same error. 
so, i fixed it with `git submodule update --init --recursive`

```
# you can create a shell script with content below!

$ git clone https://github.com/dsindex/syntaxnet.git work
$ cd work
$ git clone --recurse-submodules https://github.com/tensorflow/serving
# checkout proper version of serving
$ cd serving
$ git checkout 89e9dfbea055027bc31878ee8da66b54a701a746
$ git submodule update --init --recursive
# checkout proper version of tf_models
$ cd tf_models
$ git checkout a4b7bb9a5dd2c021edcd3d68d326255c734d0ef0

# you need to install gRPC properly
# https://tensorflow.github.io/serving/setup
# if you have a trouble, see https://github.com/dsindex/tensorflow#tensorflow-serving

# apply patch by dmansfield to serving/tf_models/syntaxnet 
$ cd serving/tf_models
$ patch -p1 < ../../api/pr250-patch-a4b7bb9a.diff.txt
$ cd ../../

# configure serving/tensorflow
$ cd serving/tensorflow
$ ./configure
$ cd ../../
```

i ensure that there is no problem up to `./configure`.

**Comment by johndpope** [comment]
@dsindex  @xiamx thanks guys
getting further now.

https://gist.github.com/johndpope/d41a7d6daf8652cbdaff41a2b063c801

https://gist.github.com/johndpope/fc1c2327a4ae255d9c44dda9b67b5288
