### ISSUE TITLE
how to find sejong_treebank.txt.v1 ??

### ISSUE THREAD

**Issue by nrobin** [dsindex/syntaxnet#20]
Hello dsindex.
I try to test your sample, but I can't found sejong_treebank.txt.v1.
where I find this file?

**Comment by dsindex** [comment]
@nrobin 

there is a license issue on the Sejong Treebank corpus. so i can't upload. 

take a look around ( in Korean )  
https://ithub.korean.go.kr/user/guide/corpus/guide1.do

**Comment by nrobin** [comment]
Is This file right ? 
전산 처리용 (수정) 세종 말뭉치 1/3

**Comment by nrobin** [comment]
It has two files. sejong.txt and sejong.pos
merge two file?

**Comment by dsindex** [comment]
https://ithub.korean.go.kr/user/corpus/referenceView.do
maybe this one.
"말뭉치"->"기타참고자료"->"현대문어_구문분석_말뭉치.zip"
pstree file format looks like

; 가계부의 틀이 달라지고 있다.
(S  (NP_SBJ (NP_MOD 가계부/NNG + 의/JKG)
        (NP_SBJ 틀/NNG + 이/JKS))
    (VP (VP 달라지/VV + 고/EC)
        (VP 있/VX + 다/EF + ./SF)))

**Comment by nrobin** [comment]
Have I something mistake??

I make sejong_treebank.txt.v1 with "현대문어_구문분석_말뭉치.zip"
first, I merged All file in "현대문어_구문분석_말뭉치.zip"
and Second removed all tag part somethng like <></>.
file has only pstree format
; 프랑스의 세계적인 의상 디자이너 엠마누엘 웅가로가 실내 장식용 직물 디자이너로 나섰다.
(S      (NP_SBJ         (NP     (NP_MOD 프랑스/NNP + 의/JKG)
                        (NP     (VNP_MOD 세계/NNG + 적/XSN + 이/VCP + ᆫ/ETM)
                                (NP     (NP 의상/NNG)
                                        (NP 디자이너/NNG))))
                (NP_SBJ         (NP 엠마누엘/NNP)
                        (NP_SBJ 웅가로/NNP + 가/JKS)))
        (VP     (NP_AJT         (NP     (NP     (NP 실내/NNG)
                                        (NP 장식/NNG + 용/XSN))
                                (NP 직물/NNG))
                        (NP_AJT 디자이너/NNG + 로/JKB))
                (VP 나서/VV + 었/EP + 다/EF + ./SF)))

and than I add line feed all " ; " start caracter as show below.

; 웅가로는 침실과 식당, 욕실에서 사용하는 갖가지 직물제품을 디자인해 최근 파리의 갤러리 라파예트백화점에서 `색의 컬렉션'이라는 이름으로 전시회
를 열었다.
(S      (NP_SBJ 웅가로/NNP + 는/JX)
        (VP     (VP     (NP_OBJ         (VP_MOD         (NP_AJT         (NP_CNJ 침실/NNG + 과/JC)
                                                (NP_AJT         (NP_CNJ 식당/NNG + ,/SP)
                                                        (NP_AJT 욕실/NNG + 에서/JKB)))
                                        (VP_MOD 사용/NNG + 하/XSV + 는/ETM))
                                (NP_OBJ         (NP 갖가지/NNG)
                                        (NP_OBJ 직물/NNG + 제품/NNG + 을/JKO)))
                        (VP 디자인/NNG + 하/XSV + 아/EC))
                (VP     (NP_AJT 최근/NNG)
                        (VP     (NP_AJT         (NP_MOD 파리/NNP + 의/JKG)
                                        (NP_AJT         (NP 갤러리/NNG)
                                                (NP_AJT 라파예트/NNP + 백화점/NNG + 에서/JKB)))
                                (VP     (NP_AJT         (VNP_MOD        (NP     (L `/SS)
                                                                (NP     (NP     (NP_MOD 색/NNG + 의/JKG)
                                                                                (NP 컬렉션/NNG))
                                                                        (R '/SS)))
                                                        (VNP_MOD 이/VCP + 라는/ETM))
                                                (NP_AJT 이름/NNG + 으로/JKB))
                                        (VP     (NP_OBJ 전시회/NNG + 를/JKO)
                                                (VP 열/VV + 었/EP + 다/EF + ./SF)))))))

; 목욕가운부터 탁자보, 냅킨, 앞치마까지 그가 디자인한 작품들에서 두드러지는 것은 색의 조화다.
(S      (NP_AJT         (NP_AJT 목욕/NNG + 가운/NNG + 부터/JX)
                (NP_AJT         (NP_CNJ 탁자보/NNG + ,/SP)
                        (NP_AJT         (NP_CNJ 냅킨/NNG + ,/SP)
                                (NP_AJT 앞치마/NNG + 까지/JX))))
        (S      (NP_SBJ         (VP_MOD         (NP_AJT         (S_MOD  (NP_SBJ 그/NP + 가/JKS)
                                                (VP_MOD 디자인/NNG + 하/XSV + ᆫ/ETM))
                                        (NP_AJT 작품/NNG + 들/XSN + 에서/JKB))
                                (VP_MOD 두드러지/VA + 는/ETM))
                        (NP_SBJ 것/NNB + 은/JX))
                (VP     (NP_MOD 색/NNG + 의/JKG)
                        (VNP 조화/NNG + 이/VCP + 다/EF + ./SF))))

..............

start traning 
./sejong/split.sh -v -v
./sejong/c2d.sh -v -v
./train_sejong.sh -v -v

after longtime, some error below

```
INFO:tensorflow:Processed 22 documents
INFO:tensorflow:Processed 367 documents
2017-03-21 13:21:08.469150: I syntaxnet/reader_ops.cc:140] Starting epoch 2
INFO:tensorflow:Processed 549 documents
INFO:tensorflow:Total processed documents: 3140
INFO:tensorflow:num correct tokens: 69410
INFO:tensorflow:total tokens: 73901
INFO:tensorflow:Seconds elapsed in evaluation: 11.09, eval metric: 93.92%
+ evaluate_pretrained_parser_by_eoj
+ for SET in training tuning test
+ cut -f8 /home/kyrha/models/syntaxnet/work/sejong/wdir/deptree.txt.v3.training
+ paste /home/kyrha/models/syntaxnet/work/sejong/tmp_p/syntaxnet-output/brain_parser/greedy/512,512-0.08-4400-0.85/parsed-training-corpus /home/kyrha/models/syntaxnet/work/sejong/wdir/deptree.txt.v3.training.deprel
+ /usr/bin/python /home/kyrha/models/syntaxnet/work/sejong/align_r.py
Traceback (most recent call last):
  File "/home/kyrha/models/syntaxnet/work/sejong/align_r.py", line 88, in <module>
    ret = spill(bucket)
  File "/home/kyrha/models/syntaxnet/work/sejong/align_r.py", line 37, in spill
    mseq,morph,_,tag,_,_,mgov,mptst,_,_,deprel = line.split('\t',10)
ValueError: need more than 10 values to unpack
```

**Comment by dsindex** [comment]
@nrobin 

```
cut -f8 ${CDIR}/sejong/wdir/deptree.txt.v3.${SET} > ${CDIR}/sejong/wdir/deptree.txt.v3.${SET}.deprel
paste ${TMP_DIR}/brain_parser/greedy/${LP_PARAMS}/parsed-${SET}-corpus ${CDIR}/sejong/wdir/deptree.txt.v3.${SET}.deprel > ${TMP_DIR}/brain_parser/greedy/${LP_PARAMS}/parsed-${SET}-corpus-add
${python} ${CDIR}/sejong/align_r.py < ${TMP_DIR}/brain_parser/greedy/${LP_PARAMS}/parsed-${SET}-corpus-add > ${TMP_DIR}/brain_parser/greedy/${LP_PARAMS}/parsed-${SET}-corpus-eoj
```

`align_r.py` reads `${TMP_DIR}/brain_parser/greedy/${LP_PARAMS}/parsed-${SET}-corpus-add` file which format should be :
```
mseq,morph,_,tag,_,_,mgov,mptst,_,_,deprel = line.split('\t',10)
```

`parsed-${SET}-corpus-add` file was generated by concatenating two files : 
```
paste ${TMP_DIR}/brain_parser/greedy/${LP_PARAMS}/parsed-${SET}-corpus ${CDIR}/sejong/wdir/deptree.txt.v3.${SET}.deprel
```

i recommend you to look at the files `${TMP_DIR}/brain_parser/greedy/${LP_PARAMS}/parsed-${SET}-corpus` and `${CDIR}/sejong/wdir/deptree.txt.v3.${SET}.deprel`

i guess `parsed-${SET}-corpus` file format is something different with expected one.

**Comment by nrobin** [comment]
I understand. When I checked, the number of tab(\t) in the file.
parsed-training-corpus-eoj has 3 per line.
parsed-tuning-corpus has 9 per line.
parsed-training-corpus-add has 10 per line. but this file end is something wrong.
35422 line below
```
1       참으로  _       MAG     MAG     _       4       AP      _       _
2       뜻밖    _       NNG     NNG     _       3       MOD     _       _       AP
3       의      _       JKG     JKG     _       4       NP_MOD  _       _       MOD
4       말      _       NNG     NNG     _       5       MOD     _       _       NP_MOD
5       이      _       VCP     VCP     _       6       MOD     _       _       MOD
6       었      _       EP      EP      _       7       MOD     _       _       MOD
7       습니다  _       EF      EF      _       8       MOD     _       _       MOD
8       .       _       SF      SF      _       0       ROOT    _       _       MOD
        VNP <- I don't know what is this???
1       세호    _       NNP     NNP     _       2       MOD     _       _
2       는      _       JX      JX      _       29      NP_SBJ  _       _       MOD
3       민수    _       NNP     NNP     _       4       MOD     _       _       NP_SBJ
4       의      _       JKG     JKG     _       5       NP_MOD  _       _       MOD
5       말      _       NNG     NNG     _       6       MOD     _       _       NP_MOD
6       처럼    _       JKB     JKB     _       10      NP_AJT  _       _       MOD
7       어쩜    _       MAG     MAG     _       10      AP      _       _       NP_AJT
8       보      _       VV      VV      _       9       MOD     _       _       AP
9       기      _       ETN     ETN     _       10      VP_SBJ  _       _       MOD
```

you right~. something corpus line is wrong.

**Comment by nrobin** [comment]
parsed-training-corpus-add has wrong struct.
At 354512 line
In the last column, the value is pushed down one line.
I guess this seems to be the cause of align_r.py error

**Comment by dsindex** [comment]
@nrobin 

i modified `align_r.py` to handle an exception naively.
(just skip error)

**Comment by nrobin** [comment]
Thank youThank you for your kindness.
I finally succeeded in model building.
modify to 2 file
1. Removed some error line in corpus sejong_treebank.txt.v1.
2. modify eval.py
Blocked frome 108 line to 112 line. and change total_sentences 
```
#       if len(a_data) != len(b_data) :
#               sys.stderr.write("len(a_data) = %s\n" % len(a_data))
#               sys.stderr.write("len(b_data) = %s\n" % len(b_data))
#               sys.stderr.write("can't compare\n")
#               sys.exit(1)

#       total_sentences = len(a_data)
        total_sentences = len(b_data)
```
                      (a_data)        >                     (b_data)
Because the deptree.txt.v2.${SET}  and parsed-${SET}-corpus-eoj had different lines.
I don't know, why it different.

```
echo "유튜브에서 임창정 노래 틀어줘" |python sejong/tagger.py | ./test_sejong.sh -v -v
..............
2017-03-23 13:41:29.879654: I syntaxnet/term_frequency_map.cc:101] Loaded 45 terms from /home/kyrha/models/syntaxnet/work/models_sejong/tag-map.
INFO:tensorflow:Processed 1 documents
INFO:tensorflow:Total processed documents: 1
INFO:tensorflow:num correct tokens: 1
INFO:tensorflow:total tokens: 8
INFO:tensorflow:Seconds elapsed in evaluation: 0.89, eval metric: 12.50%
INFO:tensorflow:Read 1 documents
Input: 유튜브 에서 임창정 노래 틀 어 주 어
Parse:
어 EC ROOT
 +-- 주 VX MOD
     +-- 어 EC MOD
         +-- 틀 VV MOD
             +-- 에서 JKB NP_AJT
             |   +-- 유튜브 NNP MOD
             +-- 노래 NNG NP_OBJ
                 +-- 임창정 NNP MOD
```

I do not know if this is a successful model.
I just hav a very poor basic knowledge of natural language processing.
Next I will try UD_korean bank.
Thank you again for your help.
