### ISSUE TITLE
Launch server with different model

### ISSUE THREAD

**Issue by peschanko** [dsindex/syntaxnet#23]
Thank you for the great tutorial!

I am able to launch

`./bazel-bin/tensorflow_serving/example/parsey_api --port=9000 ../api/parsey_model`

and it works fine with English. What changes do I need to make to start the server with a Russian model? I have tried to change files in `../api/parsey_model` with no result.

**Comment by dsindex** [comment]
@peschanko 

for a Russian model,
you need to export the model as described here
( https://github.com/dsindex/syntaxnet/blob/master/README_api.md )

and you also need to train a Russian model before exporting it.

```
prepare Russian UD corpus -> training -> export model -> launch
```

https://github.com/dsindex/syntaxnet/issues/19 : this is a related issue that may help you.

**Comment by jhowliu** [comment]
Hi @dsindex 
Is possible to use tensorflow loader to load the saved model? (not using the serving)

**Comment by dsindex** [comment]
@jhowliu

i can't find a way to load and test the syntaxnet model directly from python. 

but if you are interested in the dragnn model,
then try this one : https://github.com/dsindex/syntaxnet#dragnn

the dragnn is relatively easy to train and serve.

**Comment by jhowliu** [comment]
@dsindex 

Ok, i will try dragnn model.
And thanks for your awesome instructions.
