### ISSUE TITLE
Question about "installing syntaxnet"

### ISSUE THREAD

**Issue by robinqhuang** [dsindex/syntaxnet#29]
I am a beginner of SyntaxNet.

(1) Basically when you mention 'installing syntaxnet", you mean build syntaxnet from source and then 'pip install' ?  In other word, "Manual installation" in the https://github.com/tensorflow/models/tree/master/research/syntaxnet? Please confirm. thanks

(2) Then, my question:

What is 'Ubuntu 16.10+ binary installation" section for? I followed the section to install syntaxnet.  How do I modify your scripts in this git if I want to use binary installation?

I found binary installation installed "parser_ops.so" (part of python syntaxnet package).  Do you know where could I find the C++ API guide if I want to call APIs of parser_ops.so from C++ source code?

thanks.

**Comment by dsindex** [comment]
(1) yes, i prefered to installing from source. so, i meant ‘manual installation’.

(2) well, i guess that binary installation is a sort of normal python package for syntaxnet which was already compiled on Ubunto 16.10. but i am not sure how to modify bazel script for compilation. 

a year ago, i investigated the method how to use the syntaxnet via tensorfow serving. it was very tricky and hard. you can find some stuff in this repository here. but it can be only applied for old version of the syntaxnet. 
anyway i recommend you to use the dragnn model from python. it is much easier than the syntaxnet.

**Comment by robinqhuang** [comment]
@dsindex , what is relationship between dragnn and syntaxnet? do you have more info to use dragnn model? thanks.

**Comment by dsindex** [comment]
@robinqhuang 

you can refer : 
https://github.com/dsindex/syntaxnet#dragnn

Dragnn is built on the top of the syntaxnet for dynamic computation of graphs and easy use.
