### ISSUE TITLE
Why does it continue its training?

### ISSUE THREAD

**Issue by janerim** [dsindex/syntaxnet#30]
I didn't know why does it continue its training...
n-steps is 100000 but it keeps training over 160000
I did not modify any code and have completed the syntaxnet training perfectly.
What should I do?

![2018-01-03 10-02-01](https://user-images.githubusercontent.com/29474936/34506110-35ba2134-f06d-11e7-9ddd-08da36e8b31b.png)

![2018-01-03 09-52-54](https://user-images.githubusercontent.com/29474936/34506105-32c5a9d0-f06d-11e7-833a-dd5fd3b6397d.png)

**Comment by dsindex** [comment]
hello~

maybe you can check bellow code in dragnn_examples/train_dragnn.py

    # Set training steps
    pretrain_steps = [10000, 0]
    tagger_steps = FLAGS.n_steps
    train_steps = [tagger_steps, 8 * tagger_steps]      <--------  this set
real traning steps to 8*FLAGS.n_steps

    with tf.Session(target=FLAGS.tf_master, graph=graph) as sess:
        # Make sure to re-initialize all underlying state.
        sess.run(tf.global_variables_initializer())

        if do_restore :
            tf.logging.info('Restoring from checkpoint...')
            builder.saver.restore(sess, FLAGS.checkpoint_filename)

            prev_tagger_steps = stats[1]
            prev_parser_steps = stats[2]
            tf.logging.info('adjusting schedule from steps: %d, %d',
                            prev_tagger_steps, prev_parser_steps)
            pretrain_steps[0] = max(pretrain_steps[0] - prev_tagger_steps,
0)
            tf.logging.info('new pretrain steps: %d', pretrain_steps[0])

        trainer_lib.run_training(
              sess, trainers, annotator, evaluation.parser_summaries,
pretrain_steps,
              train_steps, training_set, tune_set, tune_set,
FLAGS.batch_size,
              summary_writer, FLAGS.report_every, builder.saver,
              FLAGS.checkpoint_filename, stats)
...


sorry for hidden information. ;;


2018-01-03 10:06 GMT+09:00 janerim <notifications@github.com>:
