### ISSUE TITLE
cannot import name graph_builder

### ISSUE THREAD

**Issue by aluminumbox** [dsindex/syntaxnet#35]
Hi @dsindex 
I read your train.sh. It calls /private/var/tmp/_bazel_aluminumbox/dbea27ee7390ed619a92467ce8d5c86b/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer. 
and then parser_trainer calls  
/private/var/tmp/_bazel_aluminumbox/dbea27ee7390ed619a92467ce8d5c86b/execroot/__main__/bazel-out/local-opt/bin/syntaxnet/parser_trainer.py.

I can run train.sh and parser_trainer. However, when I tried to debug parser_trainer.py and input the arguments in the configuration. Below error occurs:

ImportError: cannot import name graph_builder

I found that there is graph_builder and structured_graph_builder in the syntaxnet repository, but not in the python envirionment (site-packages/syntaxnet/).

Did I make mistakes during the installation? Do you have these two python scripts in your python environment?

**Comment by dsindex** [comment]
i am not sure. but, since ‘parser_train’ executable file is generated by bazel, it has own environment variables including python paths. so, you’d better check ‘parser_train’.

sorry for incomplete answer.
