### ISSUE TITLE
Parser a custom corpus

### ISSUE THREAD

**Issue by MinionAttack** [dsindex/syntaxnet#5]
Hi, first of all thanks very much for your scripts. I was dealing 2 weeks with Syntaxnet to make it work and with your files it was very easy. So, THANKS!

My question it's about parser a custom corpus. I want to parser SFU, PangLee2004 and PangLee2005. Now, I have commented:

`#pretrain_parser`
`#evaluate_pretrained_parser`
`#train_parser`
`evaluate_parser`
`#copy_model`
`close_fd`

To only execute the evaluation phase and avoid training again. I have tried to change in (corpus_folder)/context.pbtxt_p on:

`input {`
  `name: 'tagged-test-corpus'`
  `record_format: 'conll-sentence'`
 `Part {`
    `file_pattern: '/home/iago/Escritorio/Probar_Parser_Google/UT_English/en-ut-test.conllu.conv'`
  `}`
`}`

to:

`input {`
  `name: 'tagged-test-corpus'`
  `record_format: 'conll-sentence'`
 `Part {`
    `file_pattern: '/home/iago/Escritorio/Probar_Parser_Google/UT_English/en-ut-SFU.conll'` (for example)
  `}`
`}`

And then execute ~$./train_p.sh -v -v but I don't know if this is the correct way. I'm doing it right?

Thanks and regards.

**Comment by MinionAttack** [comment]
Ok, looking at closed issues I found that [https://github.com/dsindex/syntaxnet/issues/1](https://github.com/dsindex/syntaxnet/issues/1) and I dind't notice that was an ./test.sh!!!!

**Comment by dsindex** [comment]
@MinionAttack aha~  i got it :)
